### ISSUE TITLE
add "Apply" button for Interface Detail Page

### ISSUE THREAD

**Issue by hekexue** [appLhui/grunt-mock2easy#2]
Modify Interface's return data is very useful when debug the web app in local develop environment, but every time after I modify the return data, I have to click "Save" button and the page will go back to Interface list page. In fact, I want to modify the return data  more than one  time but I have to start from list page again and again. 

If there's an "Apply" button in the detail page will be a great help for everyone. When the return data modified, just click "Apply" and the modification will come into force immediately and the page stays in the detail page for next modification.

THANKS and Mock2easy is an excellent tool for web developers !

**Comment by appLhui** [comment]
I will fix on v0.3.18, thank you for your issues.
